name: Load test

on:
  push:
  workflow_dispatch:


env:
  FE_URL: "https://jobserm.github.io"
  BE_URL: "https://api-jobserm-cjtim.cloud.okteto.net"

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - run: docker run -i loadimpact/k6 run - < k6-test.js