name: Load test

on:
  push:
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - run: docker run -i loadimpact/k6 run - < k6-test.js